// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/19/2024, 11:30:53 PM
const configMerger = require("/home/projects/bolt-nativescript-js-qbywcp/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/projects/bolt-nativescript-js-qbywcp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/bolt-nativescript-js-qbywcp/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/bolt-nativescript-js-qbywcp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/bolt-nativescript-js-qbywcp/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/bolt-nativescript-js-qbywcp/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/projects/bolt-nativescript-js-qbywcp/plugins/**/*.{js,ts,mjs}","/home/projects/bolt-nativescript-js-qbywcp/composables/**/*.{js,ts,mjs}","/home/projects/bolt-nativescript-js-qbywcp/utils/**/*.{js,ts,mjs}","/home/projects/bolt-nativescript-js-qbywcp/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/projects/bolt-nativescript-js-qbywcp/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/projects/bolt-nativescript-js-qbywcp/app.config.{js,ts,mjs}"] } }));

module.exports = config
