// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 10/19/2024, 11:56:26 PM
const configMerger = require("/home/trantheanh82/cubable-mobile-light/node_modules/@nuxtjs/tailwindcss/dist/runtime/merger.js");

const inlineConfig = {"content":[],"theme":{"extend":{}},"plugins":[]};

const config = [
require("./../tailwind.config.js")
].reduce((prev, curr) => configMerger(curr, prev), configMerger(inlineConfig, { content: { files: ["/home/trantheanh82/cubable-mobile-light/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/trantheanh82/cubable-mobile-light/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/trantheanh82/cubable-mobile-light/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/trantheanh82/cubable-mobile-light/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/trantheanh82/cubable-mobile-light/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/home/trantheanh82/cubable-mobile-light/plugins/**/*.{js,ts,mjs}","/home/trantheanh82/cubable-mobile-light/composables/**/*.{js,ts,mjs}","/home/trantheanh82/cubable-mobile-light/utils/**/*.{js,ts,mjs}","/home/trantheanh82/cubable-mobile-light/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/home/trantheanh82/cubable-mobile-light/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/home/trantheanh82/cubable-mobile-light/app.config.{js,ts,mjs}"] } }));

module.exports = config
